-- Search Lights highlight definitions for Neovim
local M = {}

function M.setup(c, opts)
  opts = opts or {}
  local italic = opts.italic ~= false

  local highlights = {
    -- Editor
    Normal = { fg = c.fg0, bg = c.bg1 },
    NormalFloat = { fg = c.fg0, bg = c.bg0 },
    NormalNC = { fg = c.fg0, bg = c.bg1 },
    FloatBorder = { fg = c.border, bg = c.bg0 },
    FloatTitle = { fg = c.yellow, bg = c.bg0 },
    ColorColumn = { bg = c.bg2 },
    Conceal = { fg = c.fg4 },
    Cursor = { fg = c.bg1, bg = c.cursor },
    lCursor = { fg = c.bg1, bg = c.cursor },
    CursorIM = { fg = c.bg1, bg = c.cursor },
    CursorColumn = { bg = c.bg2 },
    CursorLine = { bg = c.bg4 },
    Directory = { fg = c.blue_light },
    DiffAdd = { fg = c.diff_add, bg = c.bg2 },
    DiffChange = { fg = c.diff_change, bg = c.bg2 },
    DiffDelete = { fg = c.diff_delete, bg = c.bg2 },
    DiffText = { fg = c.diff_text, bg = c.bg3 },
    EndOfBuffer = { fg = c.bg1 },
    ErrorMsg = { fg = c.error },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border },
    Folded = { fg = c.fg4, bg = c.bg2 },
    FoldColumn = { fg = c.fg4, bg = c.bg0 },
    SignColumn = { fg = c.fg4, bg = c.bg1 },
    IncSearch = { fg = c.bg1, bg = c.yellow },
    CurSearch = { fg = c.bg1, bg = c.yellow },
    Substitute = { fg = c.bg1, bg = c.orange },
    LineNr = { fg = c.fg4 },
    CursorLineNr = { fg = c.yellow },
    MatchParen = { fg = c.yellow, bold = true },
    ModeMsg = { fg = c.fg0 },
    MsgArea = { fg = c.fg0 },
    MoreMsg = { fg = c.green },
    NonText = { fg = c.fg4 },
    Pmenu = { fg = c.fg0, bg = c.bg0 },
    PmenuSel = { fg = c.fg1, bg = c.bg3 },
    PmenuSbar = { bg = c.bg2 },
    PmenuThumb = { bg = c.fg4 },
    Question = { fg = c.green },
    QuickFixLine = { bg = c.bg3 },
    Search = { fg = c.bg1, bg = c.yellow },
    SpecialKey = { fg = c.fg4 },
    SpellBad = { undercurl = true, sp = c.error },
    SpellCap = { undercurl = true, sp = c.warning },
    SpellLocal = { undercurl = true, sp = c.info },
    SpellRare = { undercurl = true, sp = c.hint },
    StatusLine = { fg = c.fg3, bg = c.bg0 },
    StatusLineNC = { fg = c.fg4, bg = c.bg0 },
    TabLine = { fg = c.fg3, bg = c.bg0 },
    TabLineFill = { bg = c.bg0 },
    TabLineSel = { fg = c.fg0, bg = c.bg1 },
    Title = { fg = c.yellow, bold = true },
    Visual = { bg = c.selection },
    VisualNOS = { bg = c.selection },
    WarningMsg = { fg = c.warning },
    Whitespace = { fg = c.fg4 },
    WildMenu = { fg = c.fg1, bg = c.bg3 },
    WinBar = { fg = c.fg3, bg = c.bg0 },
    WinBarNC = { fg = c.fg4, bg = c.bg0 },

    -- Syntax
    Comment = { fg = c.fg4, italic = italic },
    Constant = { fg = c.orange },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },
    Identifier = { fg = c.magenta_light },
    Function = { fg = c.blue_light },
    Statement = { fg = c.magenta },
    Conditional = { fg = c.magenta },
    Repeat = { fg = c.magenta },
    Label = { fg = c.magenta },
    Operator = { fg = c.fg1 },
    Keyword = { fg = c.magenta },
    Exception = { fg = c.magenta },
    PreProc = { fg = c.purple_light },
    Include = { fg = c.purple_light },
    Define = { fg = c.purple_light },
    Macro = { fg = c.purple_light },
    PreCondit = { fg = c.purple_light },
    Type = { fg = c.orange },
    StorageClass = { fg = c.orange, italic = italic },
    Structure = { fg = c.orange },
    Typedef = { fg = c.orange },
    Special = { fg = c.magenta },
    SpecialChar = { fg = c.yellow },
    Tag = { fg = c.yellow },
    Delimiter = { fg = c.fg0 },
    SpecialComment = { fg = c.fg4, italic = italic },
    Debug = { fg = c.orange },
    Underlined = { underline = true },
    Ignore = { fg = c.fg4 },
    Error = { fg = c.error },
    Todo = { fg = c.yellow, bold = true },

    -- TypeScript/TSX (vim syntax)
    typescriptBlock = { fg = c.fg1 },
    typescriptBraces = { fg = c.yellow },
    typescriptParens = { fg = c.yellow },
    typescriptParenExp = { fg = c.fg1 },
    typescriptEndColons = { fg = c.fg0 },
    typescriptVariable = { fg = c.magenta_light },
    typescriptIdentifier = { fg = c.magenta_light },
    typescriptIdentifierName = { fg = c.blue_light },
    typescriptFuncKeyword = { fg = c.magenta },
    typescriptOperator = { fg = c.magenta },
    typescriptKeywordOp = { fg = c.magenta },
    typescriptTypeReference = { fg = c.orange },
    typescriptPredefinedType = { fg = c.orange },

    -- TSX/JSX (vim syntax)
    tsxRegion = { fg = c.fg1 },
    tsxTag = { fg = c.orange },
    tsxEscapeJs = { fg = c.blue_light },
    tsxEscJs = { fg = c.blue_light },
    tsxTagName = { fg = c.orange },
    tsxIntrinsicTagName = { fg = c.orange },
    tsxCloseTag = { fg = c.orange },
    tsxCloseString = { fg = c.orange },
    tsxAttrib = { fg = c.magenta_light },
    tsxEqual = { fg = c.fg0 },
    tsxString = { fg = c.green },

    -- HTML (vim syntax)
    htmlTag = { fg = c.orange },
    htmlEndTag = { fg = c.orange },
    htmlTagName = { fg = c.orange },
    htmlTagN = { fg = c.orange },
    htmlSpecialTagName = { fg = c.orange },
    htmlArg = { fg = c.magenta_light },
    htmlString = { fg = c.green },

    -- Diagnostics
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.bg2 },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.bg2 },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg2 },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg2 },
    DiagnosticVirtualTextOk = { fg = c.green, bg = c.bg2 },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiagnosticUnderlineOk = { undercurl = true, sp = c.green },
    DiagnosticFloatingError = { fg = c.error },
    DiagnosticFloatingWarn = { fg = c.warning },
    DiagnosticFloatingInfo = { fg = c.info },
    DiagnosticFloatingHint = { fg = c.hint },
    DiagnosticFloatingOk = { fg = c.green },
    DiagnosticSignError = { fg = c.error },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticSignInfo = { fg = c.info },
    DiagnosticSignHint = { fg = c.hint },
    DiagnosticSignOk = { fg = c.green },

    -- LSP
    LspReferenceText = { bg = c.bg3 },
    LspReferenceRead = { bg = c.bg3 },
    LspReferenceWrite = { bg = c.bg3 },
    LspSignatureActiveParameter = { fg = c.yellow, bold = true },
    LspCodeLens = { fg = c.fg4 },
    LspCodeLensSeparator = { fg = c.fg4 },
    LspInlayHint = { fg = c.fg4, bg = c.bg2 },

    -- Treesitter
    ["@text"] = { fg = c.fg0 },
    ["@text.literal"] = { fg = c.green },
    ["@text.reference"] = { fg = c.blue_light },
    ["@text.title"] = { fg = c.yellow, bold = true },
    ["@text.uri"] = { fg = c.yellow, underline = true },
    ["@text.underline"] = { underline = true },
    ["@text.todo"] = { fg = c.yellow, bold = true },
    ["@text.note"] = { fg = c.info },
    ["@text.warning"] = { fg = c.warning },
    ["@text.danger"] = { fg = c.error },
    ["@text.diff.add"] = { fg = c.diff_add },
    ["@text.diff.delete"] = { fg = c.diff_delete },

    ["@comment"] = { fg = c.fg4, italic = italic },
    ["@punctuation"] = { fg = c.fg0 },
    ["@punctuation.delimiter"] = { fg = c.fg0 },
    ["@punctuation.bracket"] = { fg = c.yellow },
    ["@punctuation.special"] = { fg = c.yellow },

    ["@constant"] = { fg = c.orange },
    ["@constant.builtin"] = { fg = c.orange },
    ["@constant.macro"] = { fg = c.purple_light },

    ["@define"] = { fg = c.purple_light },
    ["@macro"] = { fg = c.purple_light },
    ["@string"] = { fg = c.green },
    ["@string.escape"] = { fg = c.yellow },
    ["@string.special"] = { fg = c.yellow },
    ["@string.regex"] = { fg = c.blue_light },

    ["@character"] = { fg = c.green },
    ["@character.special"] = { fg = c.yellow },
    ["@number"] = { fg = c.orange },
    ["@boolean"] = { fg = c.orange },
    ["@float"] = { fg = c.orange },

    ["@function"] = { fg = c.blue_light },
    ["@function.builtin"] = { fg = c.blue_light },
    ["@function.macro"] = { fg = c.purple_light },
    ["@function.call"] = { fg = c.blue_light },
    ["@function.method"] = { fg = c.blue_light },
    ["@function.method.call"] = { fg = c.blue_light },

    ["@parameter"] = { fg = c.fg2 },
    ["@method"] = { fg = c.blue_light },
    ["@method.call"] = { fg = c.blue_light },
    ["@field"] = { fg = c.fg0 },
    ["@property"] = { fg = c.fg1 },

    ["@constructor"] = { fg = c.red_light },
    ["@conditional"] = { fg = c.magenta },
    ["@repeat"] = { fg = c.magenta },
    ["@label"] = { fg = c.magenta },

    ["@operator"] = { fg = c.fg1 },
    ["@keyword"] = { fg = c.magenta },
    ["@keyword.function"] = { fg = c.magenta },
    ["@keyword.operator"] = { fg = c.fg1 },
    ["@keyword.return"] = { fg = c.magenta },
    ["@keyword.conditional"] = { fg = c.magenta },
    ["@keyword.repeat"] = { fg = c.magenta },
    ["@keyword.import"] = { fg = c.purple_light },
    ["@keyword.import.tsx"] = { fg = c.magenta },
    ["@keyword.exception"] = { fg = c.magenta },

    ["@exception"] = { fg = c.magenta },
    ["@variable"] = { fg = c.fg1 },
    ["@variable.tsx"] = { fg = c.fg1 },
    ["@variable.builtin"] = { fg = c.magenta_light },
    ["@variable.parameter"] = { fg = c.fg2 },
    ["@variable.member"] = { fg = c.fg0 },

    ["@type"] = { fg = c.orange },
    ["@type.tsx"] = { fg = c.blue_light },
    ["@type.definition"] = { fg = c.orange },
    ["@type.builtin"] = { fg = c.orange },
    ["@type.qualifier"] = { fg = c.magenta },
    ["@type.parameter"] = { fg = c.orange },
    ["@type.parameter.tsx"] = { fg = c.orange },
    ["@type.parameter.typescript"] = { fg = c.orange },

    ["@storageclass"] = { fg = c.orange, italic = italic },
    ["@attribute"] = { fg = c.orange },
    ["@namespace"] = { fg = c.fg0 },
    ["@include"] = { fg = c.purple_light },

    ["@preproc"] = { fg = c.purple_light },
    ["@debug"] = { fg = c.orange },
    ["@tag"] = { fg = c.red_light },
    ["@tag.builtin"] = { fg = c.yellow },
    ["@tag.attribute"] = { fg = c.orange },
    ["@tag.delimiter"] = { fg = c.red_light },

    -- JSX/TSX specific
    ["@tag.tsx"] = { fg = c.red_light },
    ["@tag.javascript"] = { fg = c.red_light },
    ["@constructor.tsx"] = { fg = c.red_light },
    ["@constructor.javascript"] = { fg = c.red_light },
    ["@punctuation.bracket.tsx"] = { fg = c.yellow },
    ["@punctuation.bracket.typescript"] = { fg = c.yellow },
    ["@punctuation.special.tsx"] = { fg = c.yellow },
    ["@punctuation.special.typescript"] = { fg = c.yellow },

    -- TypeScript/TSX treesitter specific
    ["@keyword.type"] = { fg = c.magenta },
    ["@keyword.type.tsx"] = { fg = c.magenta },
    ["@keyword.type.typescript"] = { fg = c.magenta },
    ["@keyword.modifier"] = { fg = c.magenta },
    ["@keyword.modifier.tsx"] = { fg = c.magenta },
    ["@keyword.modifier.typescript"] = { fg = c.magenta },
    ["@keyword.coroutine"] = { fg = c.magenta },
    ["@keyword.coroutine.tsx"] = { fg = c.magenta },
    ["@keyword.coroutine.typescript"] = { fg = c.magenta },
    ["@keyword.export"] = { fg = c.purple_light },
    ["@keyword.export.tsx"] = { fg = c.purple_light },
    ["@keyword.export.typescript"] = { fg = c.purple_light },
    ["@keyword.default"] = { fg = c.magenta },
    ["@module"] = { fg = c.fg0 },
    ["@module.tsx"] = { fg = c.fg0 },
    ["@module.typescript"] = { fg = c.fg0 },

    -- Modern treesitter capture names
    ["@number.float"] = { fg = c.orange },
    ["@string.special.url"] = { fg = c.yellow, underline = true },
    ["@string.special.path"] = { fg = c.green },
    ["@comment.documentation"] = { fg = c.fg4, italic = italic },
    ["@comment.error"] = { fg = c.error },
    ["@comment.warning"] = { fg = c.warning },
    ["@comment.note"] = { fg = c.info },
    ["@comment.todo"] = { fg = c.yellow, bold = true },

    -- Semantic tokens
    ["@lsp.type.class"] = { fg = c.red_light },
    ["@lsp.type.comment"] = { fg = c.fg4, italic = italic },
    ["@lsp.type.decorator"] = { fg = c.orange },
    ["@lsp.type.enum"] = { fg = c.orange },
    ["@lsp.type.enumMember"] = { fg = c.orange },
    ["@lsp.type.function"] = { fg = c.blue_light },
    ["@lsp.type.interface"] = { fg = c.red_light },
    ["@lsp.type.macro"] = { fg = c.purple_light },
    ["@lsp.type.method"] = { fg = c.blue_light },
    ["@lsp.type.namespace"] = { fg = c.fg0 },
    ["@lsp.type.parameter"] = { fg = c.fg2 },
    ["@lsp.type.property"] = { fg = c.fg1 },
    ["@lsp.type.struct"] = { fg = c.orange },
    ["@lsp.type.type"] = { fg = c.orange },
    ["@lsp.type.typeParameter"] = { fg = c.orange },
    ["@lsp.type.variable"] = { fg = c.fg1 },
    ["@lsp.type.keyword"] = { fg = c.magenta },
    ["@lsp.type.string"] = { fg = c.green },
    ["@lsp.type.number"] = { fg = c.orange },
    ["@lsp.type.regexp"] = { fg = c.blue_light },
    ["@lsp.type.operator"] = { fg = c.fg1 },

    -- LSP semantic token modifiers (TypeScript uses these heavily)
    ["@lsp.mod.declaration"] = {},
    ["@lsp.mod.definition"] = {},
    ["@lsp.mod.readonly"] = { italic = italic },
    ["@lsp.mod.static"] = { italic = italic },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.abstract"] = { italic = italic },
    ["@lsp.mod.async"] = {},
    ["@lsp.mod.modification"] = {},
    ["@lsp.mod.documentation"] = {},
    ["@lsp.mod.defaultLibrary"] = {},

    -- TypeScript-specific LSP semantic tokens
    ["@lsp.typemod.function.declaration"] = { fg = c.blue_light },
    ["@lsp.typemod.function.async"] = { fg = c.blue_light },
    ["@lsp.typemod.variable.readonly"] = { fg = c.orange },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = c.magenta_light },
    ["@lsp.typemod.class.declaration"] = { fg = c.red_light },
    ["@lsp.typemod.class.defaultLibrary"] = { fg = c.red_light },
    ["@lsp.typemod.interface.declaration"] = { fg = c.red_light },
    ["@lsp.typemod.type.declaration"] = { fg = c.orange },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = c.orange },
    ["@lsp.typemod.enum.declaration"] = { fg = c.orange },
    ["@lsp.typemod.parameter.declaration"] = { fg = c.fg2 },
    ["@lsp.typemod.property.declaration"] = { fg = c.fg1 },
    ["@lsp.typemod.method.declaration"] = { fg = c.blue_light },
    ["@lsp.typemod.method.async"] = { fg = c.blue_light },

    -- Markdown
    ["@markup.heading"] = { fg = c.yellow, bold = true },
    ["@markup.heading.1"] = { fg = c.yellow, bold = true },
    ["@markup.heading.2"] = { fg = c.orange, bold = true },
    ["@markup.heading.3"] = { fg = c.magenta, bold = true },
    ["@markup.heading.4"] = { fg = c.blue_light, bold = true },
    ["@markup.heading.5"] = { fg = c.purple_light, bold = true },
    ["@markup.heading.6"] = { fg = c.green, bold = true },
    ["@markup.quote"] = { fg = c.fg3, italic = italic },
    ["@markup.math"] = { fg = c.blue_light },
    ["@markup.link"] = { fg = c.yellow },
    ["@markup.link.label"] = { fg = c.blue_light },
    ["@markup.link.url"] = { fg = c.yellow, underline = true },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.raw.block"] = { fg = c.green },
    ["@markup.list"] = { fg = c.magenta },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.fg4 },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },

    -- Git Signs
    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.git_change },
    GitSignsDelete = { fg = c.git_delete },
    GitSignsAddNr = { fg = c.git_add },
    GitSignsChangeNr = { fg = c.git_change },
    GitSignsDeleteNr = { fg = c.git_delete },
    GitSignsAddLn = { fg = c.git_add, bg = c.bg2 },
    GitSignsChangeLn = { fg = c.git_change, bg = c.bg2 },
    GitSignsDeleteLn = { fg = c.git_delete, bg = c.bg2 },
    GitSignsCurrentLineBlame = { fg = c.fg4, italic = italic },

    -- Indent Blankline
    IndentBlanklineChar = { fg = c.bg3 },
    IndentBlanklineContextChar = { fg = c.fg4 },
    IndentBlanklineContextStart = { sp = c.fg4, underline = true },
    IblIndent = { fg = c.bg3 },
    IblScope = { fg = c.fg4 },

    -- Which-key
    WhichKey = { fg = c.yellow },
    WhichKeyGroup = { fg = c.blue_light },
    WhichKeyDesc = { fg = c.fg0 },
    WhichKeySeperator = { fg = c.fg4 },
    WhichKeySeparator = { fg = c.fg4 },
    WhichKeyFloat = { bg = c.bg0 },
    WhichKeyValue = { fg = c.fg3 },

    -- Lazy
    LazyH1 = { fg = c.bg1, bg = c.yellow, bold = true },
    LazyButton = { fg = c.fg0, bg = c.bg3 },
    LazyButtonActive = { fg = c.bg1, bg = c.yellow },
    LazySpecial = { fg = c.magenta },
    LazyProgressDone = { fg = c.yellow },
    LazyProgressTodo = { fg = c.fg4 },

    -- Mason
    MasonHeader = { fg = c.bg1, bg = c.yellow, bold = true },
    MasonHeaderSecondary = { fg = c.bg1, bg = c.blue_light, bold = true },
    MasonHighlight = { fg = c.blue_light },
    MasonHighlightBlock = { fg = c.bg1, bg = c.blue_light },
    MasonHighlightBlockBold = { fg = c.bg1, bg = c.blue_light, bold = true },
    MasonMuted = { fg = c.fg4 },
    MasonMutedBlock = { fg = c.fg4, bg = c.bg2 },

    -- Notify
    NotifyERRORBorder = { fg = c.error },
    NotifyWARNBorder = { fg = c.warning },
    NotifyINFOBorder = { fg = c.info },
    NotifyDEBUGBorder = { fg = c.fg4 },
    NotifyTRACEBorder = { fg = c.purple_light },
    NotifyERRORIcon = { fg = c.error },
    NotifyWARNIcon = { fg = c.warning },
    NotifyINFOIcon = { fg = c.info },
    NotifyDEBUGIcon = { fg = c.fg4 },
    NotifyTRACEIcon = { fg = c.purple_light },
    NotifyERRORTitle = { fg = c.error },
    NotifyWARNTitle = { fg = c.warning },
    NotifyINFOTitle = { fg = c.info },
    NotifyDEBUGTitle = { fg = c.fg4 },
    NotifyTRACETitle = { fg = c.purple_light },

    -- nvim-cmp
    CmpItemAbbr = { fg = c.fg0 },
    CmpItemAbbrDeprecated = { fg = c.fg4, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.yellow, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.yellow, bold = true },
    CmpItemMenu = { fg = c.fg4 },
    CmpItemKindDefault = { fg = c.fg3 },
    CmpItemKindKeyword = { fg = c.magenta },
    CmpItemKindVariable = { fg = c.fg1 },
    CmpItemKindConstant = { fg = c.orange },
    CmpItemKindReference = { fg = c.fg1 },
    CmpItemKindValue = { fg = c.orange },
    CmpItemKindFunction = { fg = c.blue_light },
    CmpItemKindMethod = { fg = c.blue_light },
    CmpItemKindConstructor = { fg = c.red_light },
    CmpItemKindClass = { fg = c.red_light },
    CmpItemKindInterface = { fg = c.red_light },
    CmpItemKindStruct = { fg = c.orange },
    CmpItemKindEvent = { fg = c.magenta },
    CmpItemKindEnum = { fg = c.orange },
    CmpItemKindUnit = { fg = c.orange },
    CmpItemKindModule = { fg = c.fg0 },
    CmpItemKindProperty = { fg = c.fg1 },
    CmpItemKindField = { fg = c.fg0 },
    CmpItemKindTypeParameter = { fg = c.orange },
    CmpItemKindEnumMember = { fg = c.orange },
    CmpItemKindOperator = { fg = c.fg1 },
    CmpItemKindSnippet = { fg = c.green },
    CmpItemKindText = { fg = c.fg0 },
    CmpItemKindFile = { fg = c.blue_light },
    CmpItemKindFolder = { fg = c.blue_light },
    CmpItemKindColor = { fg = c.magenta },

    -- Flash
    FlashBackdrop = { fg = c.fg4 },
    FlashLabel = { fg = c.bg1, bg = c.yellow, bold = true },
    FlashMatch = { fg = c.yellow, bg = c.bg3 },
    FlashCurrent = { fg = c.orange, bg = c.bg3 },

    -- Mini
    MiniStatuslineDevinfo = { fg = c.fg0, bg = c.bg3 },
    MiniStatuslineFileinfo = { fg = c.fg0, bg = c.bg3 },
    MiniStatuslineFilename = { fg = c.fg3, bg = c.bg2 },
    MiniStatuslineInactive = { fg = c.fg4, bg = c.bg0 },
    MiniStatuslineModeCommand = { fg = c.bg1, bg = c.orange, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg1, bg = c.green, bold = true },
    MiniStatuslineModeNormal = { fg = c.bg1, bg = c.yellow, bold = true },
    MiniStatuslineModeOther = { fg = c.bg1, bg = c.purple_light, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg1, bg = c.red_light, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg1, bg = c.magenta, bold = true },

    -- Noice
    NoiceCmdline = { fg = c.fg0 },
    NoiceCmdlineIcon = { fg = c.yellow },
    NoiceCmdlineIconSearch = { fg = c.yellow },
    NoiceCmdlinePopup = { fg = c.fg0, bg = c.bg0 },
    NoiceCmdlinePopupBorder = { fg = c.border },
    NoiceCmdlinePopupBorderSearch = { fg = c.yellow },
    NoiceConfirm = { fg = c.fg0, bg = c.bg0 },
    NoiceConfirmBorder = { fg = c.yellow },

    -- Rainbow delimiters
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterCyan = { fg = c.cyan },
    RainbowDelimiterViolet = { fg = c.purple },
    RainbowDelimiterRed = { fg = c.magenta },
    RainbowDelimiterGreen = { fg = c.green_soft },
    RainbowDelimiterBlue = { fg = c.blue_bright },
    RainbowDelimiterOrange = { fg = c.orange },

    -- vim-devicons / nvim-web-devicons
    DevIconDefault = { fg = c.fg3 },
    DevIconJs = { fg = c.yellow },
    DevIconTs = { fg = c.cyan },
    DevIconTsx = { fg = c.cyan },
    DevIconJsx = { fg = c.yellow },
    DevIconJson = { fg = c.yellow },
    DevIconLua = { fg = c.blue_bright },
    DevIconPy = { fg = c.yellow },
    DevIconRb = { fg = c.red_light },
    DevIconRs = { fg = c.orange },
    DevIconGo = { fg = c.cyan },
    DevIconHtml = { fg = c.orange },
    DevIconCss = { fg = c.purple_light },
    DevIconScss = { fg = c.magenta },
    DevIconSass = { fg = c.magenta },
    DevIconLess = { fg = c.purple_light },
    DevIconMd = { fg = c.cyan },
    DevIconMarkdown = { fg = c.cyan },
    DevIconYml = { fg = c.magenta },
    DevIconYaml = { fg = c.magenta },
    DevIconToml = { fg = c.orange },
    DevIconGitIgnore = { fg = c.red_light },
    DevIconGitAttributes = { fg = c.red_light },
    DevIconDockerfile = { fg = c.cyan },
    DevIconVim = { fg = c.green },
    DevIconSh = { fg = c.green },
    DevIconBash = { fg = c.green },
    DevIconZsh = { fg = c.green },
    DevIconTxt = { fg = c.fg0 },
    DevIconLicense = { fg = c.yellow },
    DevIconPackageJson = { fg = c.green },
    DevIconPackageLockJson = { fg = c.red_light },
    DevIconEnv = { fg = c.yellow },
    DevIconSvg = { fg = c.orange },
    DevIconPng = { fg = c.purple_light },
    DevIconJpg = { fg = c.purple_light },
    DevIconGif = { fg = c.purple_light },
    DevIconWebp = { fg = c.purple_light },
    DevIconIco = { fg = c.yellow },
    DevIconConf = { fg = c.fg3 },
    DevIconConfiguration = { fg = c.fg3 },
  }

  return highlights
end

return M
