-- coc.nvim and coc-explorer highlights for Search Lights
local M = {}

function M.setup(c)
  return {
    -- coc.nvim general
    CocErrorSign = { fg = c.error },
    CocWarningSign = { fg = c.warning },
    CocInfoSign = { fg = c.info },
    CocHintSign = { fg = c.hint },
    CocErrorFloat = { fg = c.error },
    CocWarningFloat = { fg = c.warning },
    CocInfoFloat = { fg = c.info },
    CocHintFloat = { fg = c.hint },
    CocErrorHighlight = { undercurl = true, sp = c.error },
    CocWarningHighlight = { undercurl = true, sp = c.warning },
    CocInfoHighlight = { undercurl = true, sp = c.info },
    CocHintHighlight = { undercurl = true, sp = c.hint },
    CocErrorVirtualText = { fg = c.error },
    CocWarningVirtualText = { fg = c.warning },
    CocInfoVirtualText = { fg = c.info },
    CocHintVirtualText = { fg = c.hint },
    CocErrorLine = { bg = c.bg2 },
    CocWarningLine = { bg = c.bg2 },
    CocInfoLine = { bg = c.bg2 },
    CocHintLine = { bg = c.bg2 },

    -- coc floating windows
    CocFloating = { fg = c.fg0, bg = c.bg0 },
    CocFloatThumb = { bg = c.fg4 },
    CocFloatSbar = { bg = c.bg2 },
    CocFloatDividingLine = { fg = c.border },

    -- coc menu
    CocMenuSel = { fg = c.fg1, bg = c.bg3 },
    CocPumSearch = { fg = c.yellow, bold = true },
    CocPumDetail = { fg = c.fg4 },
    CocPumMenu = { fg = c.fg4 },
    CocPumShortcut = { fg = c.fg4 },
    CocPumDeprecated = { fg = c.fg4, strikethrough = true },
    CocPumVirtualText = { fg = c.fg4 },

    -- coc symbols
    CocSymbolFile = { fg = c.blue_light },
    CocSymbolModule = { fg = c.fg0 },
    CocSymbolNamespace = { fg = c.fg0 },
    CocSymbolPackage = { fg = c.fg0 },
    CocSymbolClass = { fg = c.red_light },
    CocSymbolMethod = { fg = c.blue_light },
    CocSymbolProperty = { fg = c.fg1 },
    CocSymbolField = { fg = c.fg0 },
    CocSymbolConstructor = { fg = c.red_light },
    CocSymbolEnum = { fg = c.orange },
    CocSymbolInterface = { fg = c.red_light },
    CocSymbolFunction = { fg = c.blue_light },
    CocSymbolVariable = { fg = c.fg1 },
    CocSymbolConstant = { fg = c.orange },
    CocSymbolString = { fg = c.green },
    CocSymbolNumber = { fg = c.orange },
    CocSymbolBoolean = { fg = c.orange },
    CocSymbolArray = { fg = c.orange },
    CocSymbolObject = { fg = c.orange },
    CocSymbolKey = { fg = c.magenta },
    CocSymbolNull = { fg = c.orange },
    CocSymbolEnumMember = { fg = c.orange },
    CocSymbolStruct = { fg = c.orange },
    CocSymbolEvent = { fg = c.magenta },
    CocSymbolOperator = { fg = c.fg1 },
    CocSymbolTypeParameter = { fg = c.orange },
    CocSymbolDefault = { fg = c.fg0 },

    -- coc inlay hints
    CocInlayHint = { fg = c.fg4, bg = c.bg2 },
    CocInlayHintType = { fg = c.fg4, bg = c.bg2 },
    CocInlayHintParameter = { fg = c.fg4, bg = c.bg2 },

    -- coc misc
    CocHighlightText = { bg = c.bg3 },
    CocHighlightRead = { bg = c.bg3 },
    CocHighlightWrite = { bg = c.bg3 },
    CocCodeLens = { fg = c.fg4 },
    CocCursorRange = { bg = c.selection },
    CocLinkedEditing = { bg = c.bg3 },
    CocSearch = { fg = c.yellow },
    CocNotificationProgress = { fg = c.blue_light },
    CocNotificationButton = { fg = c.fg0, bg = c.bg3 },
    CocNotificationError = { fg = c.error },
    CocNotificationWarning = { fg = c.warning },
    CocNotificationInfo = { fg = c.info },

    -- coc git
    CocGitAddedSign = { fg = c.git_add },
    CocGitChangedSign = { fg = c.git_change },
    CocGitRemovedSign = { fg = c.git_delete },
    CocGitTopRemovedSign = { fg = c.git_delete },
    CocGitChangeRemovedSign = { fg = c.git_change },

    -- coc-explorer
    CocExplorerNormalFloatBorder = { fg = c.border, bg = c.bg0 },
    CocExplorerNormalFloat = { fg = c.fg0, bg = c.bg0 },
    CocExplorerBufferRoot = { fg = c.yellow, bold = true },
    CocExplorerBufferRootName = { fg = c.yellow, bold = true },
    CocExplorerBufferExpandIcon = { fg = c.blue_light },
    CocExplorerBufferBufnr = { fg = c.fg4 },
    CocExplorerBufferModified = { fg = c.orange },
    CocExplorerBufferBufname = { fg = c.fg0 },
    CocExplorerBufferFullpath = { fg = c.fg3 },

    CocExplorerFileRoot = { fg = c.yellow, bold = true },
    CocExplorerFileRootName = { fg = c.yellow, bold = true },
    CocExplorerFileExpandIcon = { fg = c.blue_light },
    CocExplorerFileFullpath = { fg = c.fg3 },
    CocExplorerFileDirectory = { fg = c.blue_light },
    CocExplorerFileDirectoryExpanded = { fg = c.blue_light },
    CocExplorerFileDirectoryCollapsed = { fg = c.blue_light },
    CocExplorerFileGitStaged = { fg = c.git_add },
    CocExplorerFileGitUnstaged = { fg = c.git_change },
    CocExplorerFileGitRootStaged = { fg = c.git_add },
    CocExplorerFileGitRootUnstaged = { fg = c.git_change },
    CocExplorerFileFilename = { fg = c.fg0 },
    CocExplorerFileFilenameModified = { fg = c.orange },
    CocExplorerFileSize = { fg = c.fg3 },
    CocExplorerFileModified = { fg = c.blue_light },
    CocExplorerFileReadonly = { fg = c.fg4 },
    CocExplorerFileHidden = { fg = c.fg4 },
    CocExplorerFileSymlink = { fg = c.purple_light },
    CocExplorerFileLinkTarget = { fg = c.fg4 },

    CocExplorerGitPathChange_Internal = { fg = c.git_change },
    CocExplorerGitPathChange_Staged = { fg = c.git_add },
    CocExplorerGitPathChange_Unstaged = { fg = c.git_change },
    CocExplorerGitContentChange_Staged = { fg = c.git_add },
    CocExplorerGitContentChange_Unstaged = { fg = c.git_change },
    CocExplorerGitRenamed = { fg = c.git_change },
    CocExplorerGitCopied = { fg = c.git_add },
    CocExplorerGitAdded = { fg = c.git_add },
    CocExplorerGitUntracked = { fg = c.git_add },
    CocExplorerGitUnmodified = { fg = c.fg0 },
    CocExplorerGitUnmerged = { fg = c.git_conflict },
    CocExplorerGitMixed = { fg = c.git_change },
    CocExplorerGitModified = { fg = c.git_change },
    CocExplorerGitDeleted = { fg = c.git_delete },
    CocExplorerGitIgnored = { fg = c.fg4 },

    CocExplorerIndentLine = { fg = c.bg3 },
    CocExplorerHelpHint = { fg = c.fg4 },
    CocExplorerHelpDescription = { fg = c.fg3 },
    CocExplorerSelectUI = { fg = c.yellow },
    CocExplorerDiagnosticError = { fg = c.error },
    CocExplorerDiagnosticWarning = { fg = c.warning },

    -- coc list (used by many coc extensions)
    CocListLine = { bg = c.bg3 },
    CocListSearch = { fg = c.yellow, bold = true },
    CocListMode = { fg = c.bg1, bg = c.yellow, bold = true },
    CocListPath = { fg = c.fg3 },
    CocListBlackBlack = { fg = c.bg0, bg = c.bg0 },
    CocListBlackWhite = { fg = c.bg0, bg = c.fg0 },
    CocListBlackGreen = { fg = c.bg0, bg = c.green },
    CocListBlackRed = { fg = c.bg0, bg = c.red_light },
    CocListBlackYellow = { fg = c.bg0, bg = c.yellow },
    CocListBlackBlue = { fg = c.bg0, bg = c.blue_light },
    CocListBlackMagenta = { fg = c.bg0, bg = c.magenta },
    CocListBlackCyan = { fg = c.bg0, bg = c.cyan },
    CocListBlackGrey = { fg = c.bg0, bg = c.fg4 },
    CocListFgBlack = { fg = c.bg0 },
    CocListFgWhite = { fg = c.fg1 },
    CocListFgGreen = { fg = c.green },
    CocListFgRed = { fg = c.red_light },
    CocListFgYellow = { fg = c.yellow },
    CocListFgBlue = { fg = c.blue_light },
    CocListFgMagenta = { fg = c.magenta },
    CocListFgCyan = { fg = c.cyan },
    CocListFgGrey = { fg = c.fg4 },
    CocListBgBlack = { bg = c.bg0 },
    CocListBgWhite = { bg = c.fg1 },
    CocListBgGreen = { bg = c.green },
    CocListBgRed = { bg = c.red_light },
    CocListBgYellow = { bg = c.yellow },
    CocListBgBlue = { bg = c.blue_light },
    CocListBgMagenta = { bg = c.magenta },
    CocListBgCyan = { bg = c.cyan },
    CocListBgGrey = { bg = c.fg4 },

    -- coc outline
    CocOutlineName = { fg = c.fg0 },
    CocOutlineIndentLine = { fg = c.bg3 },
    CocOutlineKind = { fg = c.fg4 },

    -- coc semantic tokens
    CocSemClass = { fg = c.red_light },
    CocSemComment = { fg = c.fg4 },
    CocSemDecorator = { fg = c.orange },
    CocSemEnum = { fg = c.orange },
    CocSemEnumMember = { fg = c.orange },
    CocSemEvent = { fg = c.magenta },
    CocSemFunction = { fg = c.blue_light },
    CocSemInterface = { fg = c.red_light },
    CocSemKeyword = { fg = c.magenta },
    CocSemMacro = { fg = c.purple_light },
    CocSemMethod = { fg = c.blue_light },
    CocSemModifier = { fg = c.fg4 },
    CocSemNamespace = { fg = c.fg0 },
    CocSemNumber = { fg = c.orange },
    CocSemOperator = { fg = c.fg1 },
    CocSemParameter = { fg = c.fg2 },
    CocSemProperty = { fg = c.fg1 },
    CocSemRegexp = { fg = c.blue_light },
    CocSemString = { fg = c.green },
    CocSemStruct = { fg = c.orange },
    CocSemType = { fg = c.orange },
    CocSemTypeParameter = { fg = c.orange },
    CocSemVariable = { fg = c.fg1 },
  }
end

return M
